services:

  btcpayserver:
    restart: unless-stopped
    image: lalanza808/btcpayserver-wownero:v2.0.4
    environment:
      BTCPAY_POSTGRES: User ID=postgres;Host=postgres;Port=5432;Application Name=btcpayserver;Database=btcpayserver${NBITCOIN_NETWORK:-mainnet}
      BTCPAY_NETWORK: ${NBITCOIN_NETWORK:-mainnet}
      BTCPAY_HOST: ${BTCPAY_HOST}
      BTCPAY_BIND: 0.0.0.0:49392
      BTCPAY_ROOTPATH: ${BTCPAY_ROOTPATH:-/}
      BTCPAY_SSHCONNECTION: root@host.docker.internal
      BTCPAY_SSHTRUSTEDFINGERPRINTS: ${BTCPAY_SSHTRUSTEDFINGERPRINTS}
      BTCPAY_SSHKEYFILE: ${BTCPAY_SSHKEYFILE}
      BTCPAY_SSHAUTHORIZEDKEYS: ${BTCPAY_SSHAUTHORIZEDKEYS}
      BTCPAY_DEBUGLOG: btcpay.log
      BTCPAY_UPDATEURL: https://api.github.com/repos/lalanza808/btcpayserver/releases/latest
      BTCPAY_DOCKERDEPLOYMENT: true
      BTCPAY_CHAINS: wow
      BTCPAY_WOW_DAEMON_URI: ${WOW_DAEMON_URI:-http://node.suchwow.xyz:34568}
      BTCPAY_WOW_WALLET_DAEMON_URI: http://wallet:8000
      BTCPAY_WOW_WALLET_DAEMON_WALLETDIR: /wallet/wow
    ports:
      - 127.0.0.1:49392:49392
    links:
      - postgres
    volumes:
      - btcpay_datadir:/datadir
      - btcpay_pluginsdir:/root/.btcpayserver/Plugins
      - ./data/wallet:/wallet/wow

  wallet:
    restart: unless-stopped
    image: lalanza808/btcpayserver-wownero-wallet:v0.11.3.0
    container_name: btcpayserver_wallet
    volumes:
      - ./data/wallet:/wallet
    command:
      bash /run_wallet.sh "${WOW_DAEMON_URI:-http://node.suchwow.xyz:34568}" "${WOW_WALLET_PASS:-walletpass}"

  postgres:
    restart: unless-stopped
    image: btcpayserver/postgres:13.13
    container_name: btcpayserver_postgres
    shm_size: 256mb
    command: ["-c", "random_page_cost=1.0", "-c", "shared_preload_libraries=pg_stat_statements"]
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - postgres_datadir:/var/lib/postgresql/data

volumes:
  btcpay_datadir:
  btcpay_pluginsdir:
  postgres_datadir:

networks: {}

