services:

  btcpayserver:
    restart: unless-stopped
    build:
      context: btcpayserver
    container_name: btcpayserver
    expose:
      - 49392
    environment:
      BTCPAY_POSTGRES: User ID=postgres;Host=postgres;Port=5432;Application Name=btcpayserver;Database=btcpayserver${NBITCOIN_NETWORK:-mainnet}
      BTCPAY_NETWORK: ${NBITCOIN_NETWORK:-mainnet}
      BTCPAY_BIND: 0.0.0.0:49392
      BTCPAY_ROOTPATH: ${BTCPAY_ROOTPATH:-/}
      BTCPAY_SSHCONNECTION: root@host.docker.internal
      BTCPAY_SSHTRUSTEDFINGERPRINTS: ${BTCPAY_SSHTRUSTEDFINGERPRINTS}
      BTCPAY_SSHKEYFILE: ${BTCPAY_SSHKEYFILE}
      BTCPAY_SSHAUTHORIZEDKEYS: ${BTCPAY_SSHAUTHORIZEDKEYS}
      BTCPAY_DEBUGLOG: btcpay.log
      BTCPAY_UPDATEURL: https://api.github.com/repos/lalanza808/btcpayserver/releases/latest
      BTCPAY_DOCKERDEPLOYMENT: true
      BTCPAY_CHAINS: wow
      BTCPAY_WOW_DAEMON_URI: http://wownerod:34568
      BTCPAY_WOW_WALLET_DAEMON_URI: http://wallet:8000
      BTCPAY_WOW_WALLET_DAEMON_WALLETDIR: /wallet
    ports:
      - 127.0.0.1:49392:49392
    links:
      - postgres
    volumes:
      - btcpay_datadir:/datadir
      - btcpay_pluginsdir:/root/.btcpayserver/Plugins
      - ./data/wallet:/wallet

  wownerod:
    restart: unless-stopped
    build:
      context: .
    container_name: btcpayserver_wownerod
    entrypoint: wownerod --rpc-bind-ip=0.0.0.0 --confirm-external-bind --rpc-bind-port=34568 --non-interactive --block-notify="/usr/bin/curl -s -X GET http://btcpayserver:49392/wownerolikedaemoncallback/block?cryptoCode=wow&hash=%s" --hide-my-port --enable-dns-blocklist
    expose:
      - 34568
    ports:
      - 0.0.0.0:34568:34568
    volumes:
      - ${DATA_PATH:-./data/blockchain}:/root/.wownero

  wallet:
    restart: unless-stopped
    build:
      context: .
    container_name: btcpayserver_wallet
    expose:
      - 8000
    volumes:
      - ./data/wallet:/wallet
    depends_on:
      - wownerod
    command:
      bash /run_wallet.sh "http://wownerod:34568" "${WALLET_PASS:-walletpass}"

  postgres:
    restart: unless-stopped
    image: btcpayserver/postgres:13.13
    container_name: btcpayserver_postgres
    shm_size: 256mb
    command: ["-c", "random_page_cost=1.0", "-c", "shared_preload_libraries=pg_stat_statements"]
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - postgres_datadir:/var/lib/postgresql/data

volumes:
  btcpay_datadir:
  btcpay_pluginsdir:
  postgres_datadir:

networks: {}

